import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {RxCross2} from "react-icons/rx";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiFillMail,
} from "react-icons/ai";
import Image from "next/image";
import jesh from "../public/jesh.jpg";
import code from "../public/web_dev.png";
import Dataanalysis from "../public/data_analysis.png";
import MachineLearning from "../public/machine_learning.png";
import { useState } from "react";
import {
  VerticalTimeline,
  VerticalTimelineElement,
} from "react-vertical-timeline-component";
import "react-vertical-timeline-component/style.min.css";
import Accordion from "react-bootstrap/Accordion";
import "bootstrap/dist/css/bootstrap.min.css";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [showsidebar, setshowsidebar ] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jeshmitha Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script noModule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen ">
          <nav className="fixed top-0 left-0 bg-white w-full shadow p-4 z-40">
            {/*<h1 className="text-xl font-burtons dark:text-white"> 
              developedbyJeshmitha
           </h1>*/}
            <div className="flex justify-between items-center "> 
            <div className="text-xl font-burtons dark:text-white cursor-pointer flex justify-center gap-3 py-2 dark:text-white">
            developed by Jeshmitha
            <a className="text-4xl bg-gradient-to-r from-cyan-500 to-teal-500 text-gray-600 text-white" href="https://www.linkedin.com/in/jeshmitha/"> <AiFillLinkedin  /></a>
            <a className="text-4xl bg-gradient-to-r from-cyan-500 to-teal-500 text-gray-600 text-white" href="https://github.com/jeshmitha"> <AiFillGithub /></a>
            <a className="text-4xl bg-gradient-to-r from-cyan-500 to-teal-500 text-gray-600 text-white" href="mailto: jeshmitha.gunuganti@gmail.com"> <AiFillMail /> </a>
            </div>
            
            <ul className="hidden md:flex items-center pr-10 text-base font-semibold cursor-pointer">
            <li className="mx-4 my-6 md:my-0">
                <a className="text-2xl font-burtons text-gray-900 hover:text-cyan-600 duration-500 no-underline "
                  href="#skill">Skills </a>
              </li>
              <li className="mx-4 my-6 md:my-0">
                <a className="text-2xl font-burtons text-gray-900 hover:text-cyan-600 duration-500 no-underline"
                  href="#career">Career </a>
              </li>
              <li className="mx-4 my-6 md:my-0">
                <a className="text-2xl font-burtons text-gray-900 hover:text-cyan-600 duration-500 no-underline"
                  href="#portfolio">Portfolio </a>
              </li>
              <li className="mx-4 my-6 md:my-0">
                <a className="text-2xl font-burtons text-gray-900 hover:text-cyan-600 duration-500 no-underline"
                  href="#getintouch">Get in Touch</a>
              </li>
              {/* <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li> */}
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 no-underline"
                  href="/Jeshmitha_Resume.pdf"
                  download >
                  Resume
                </a>
              </li>
              
            </ul>
            <button onClick={(e)=>setshowsidebar(true)} className="block md:hidden py-3 px-4 mx-2 rounded focus:outline-none hover:bg-gray-200 group relative"> 
              <div className="w-5 h-1 bg-gray-600 mb-1"> </div>
              <div className="w-5 h-1 bg-gray-600 mb-1"> </div>
              <div className="w-5 h-1 bg-gray-600"> </div>
              
            </button>
            <div className={`fixed top-0  -right-full h-screen w-8/12 bg-white border transform transition-all duration-300 ${showsidebar && "right-0" }`}> 
               <button onClick={(e)=>setshowsidebar(false)} className=" text-2xl absolute right-4 top-4 cursor-pointer"> <RxCross2></RxCross2> </button> 
               <ul className="flex flex-col items-center w-full text-base cursor-pointer pt-10">
               <a className="no-underline text-gray-800" href="#skill" > <li className="hover:bg-gray-200 py-4 px-6 w-full">Skills </li> </a>
                <a className="no-underline text-gray-800" href="#career" ><li className="hover:bg-gray-200 py-4 px-6 w-full">Career </li></a>
               <a className="no-underline text-gray-800" href="#portfolio"><li className="hover:bg-gray-200 py-4 px-6 w-full">Portfolio</li></a>
               <a className="no-underline text-gray-800" href="#getintouch"><li className="hover:bg-gray-200 py-4 px-6 w-full">Get in Touch </li></a>
                <a className="no-underline text-gray-800" href="/Resume_Jeshmitha.pdf" download><li className="hover:bg-gray-200 py-4 px-6 w-full">Resume</li></a>
               </ul>
              </div>
            </div>
          </nav>
          {/*<script> 
            function Menu(e){

              let list =document.querySelector('ul');
               e.name ==='menu' ? (e.name="close" ,list.classlist.add('top-[80px]'),list.classlist.add('')) : e.name ="menu",list.classList.remove('top-[80px]'))
            }
          </script>*/}
          <div className="text-left mt-28">
            <h2 className="text-center font-serif text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              JESHMITHA GUNUGANTI
            </h2>
            
            <h3 className="text-center font-serif text-xl py-0 md:text-xl dark:text-white">
              Machine Learning Engineer
            </h3>
            <h3 className="flex text-center justify-center text-sm py-0 md:text-sm dark:text-white">
            <svg xmlns="http://www.w3.org/2000/svg" className="flex text-center h-5 w-5 mr-1" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd"></path>
              </svg>
              United States
            </h3>
            <div className="float-left relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 dark:text-white">
            <Image alt=" " src={jesh} layout="fill" objectFit="cover" />
            </div>
          
            <div>
            <p className="flex text-justify text-md pl-10 leading-8 mt-8 text-gray-800 dark:text-white">
            I'm a Data Science Grad student and work as a Machine Learning Engineer at the University of Cincinnati. 
            My research currently is on 'Video Summarization,' which involves developing an unsupervised deep learning model for the automatic generation of video summaries. 
            I have experience developing ML solutions for Video, Audio, and NLP tasks from my projects and experience.
            </p>
            <p className="flex text-justify text-md pl-10 leading-8 text-gray-800 dark:text-white">
            Being a person who always tries to complete tasks in an optimized/intelligent manner, it has always been my dream to be able to use my skills to develop AI-powered systems that can optimize and speed up our lives by transforming data into valuable assets.
            </p>
            <p className="flex text-justify text-md pl-10 leading-8 text-gray-800 dark:text-white">
            As an ML engineer, I worked on building machine learning solutions and developed end-to-end data-driven products on cloud environments - AWS. 
            Training the chatbot with vast amounts of data, detecting the customers' emotions, and drawing insights from social media has given me immense experience as a data scientist and a cloud architect. 
            I also gained experience in software development working at Amazon Inc. 
            </p>
            </div>

          

          </div>
        </section>
        <section className="pt-2" id="skill" >
          <div>
            <h3 className="text-3xl py-1 dark:text-white">SKILLS</h3>
          </div>
          <div className="lg:grid lg:grid-cols-4 gap-x-10 gap-y-0 dark:text-white">
            <div className="flex flex-col items-center text-center shadow-lg p-5 rounded-xl my-5 dark:bg-white">
              <Image
                alt=" "
                className="rounded-md"
                src={Dataanalysis}
                width={80}
                height={80}
              />
              <h3 className=" text-gray-800 text-lg font-medium pt-2">
                Data Analysis
              </h3>
              <h5 className=" text-gray-700 text-sm font-normal pb-2">
                Using
              </h5>
              <div className="grid grid-cols-2 gap-2" >
              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                {/* Numpy{" "} */}
                <div className="mx-auto">
                  <Image alt=" " src={"/numpy.png"} width={40} height={40} className="mx-auto rounded-md" />
                </div>
                <div>
                  Numpy
                </div>
              </div>
              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                {/* Pandas{" "} */}
                <div className="mx-auto">
                <Image alt=" " src={"/Pandas.png"} width={40} height={40} className="mx-auto rounded-md"/>
                </div>
                <div>
                  Pandas
                </div>
              </div>
              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                {/* Matplotlib */}
                <div className="mx-auto">
                <Image alt=" " src={"/matplotlib.png"} width={40} height={40} className="mx-auto"/>
                </div>
                <div>
                  Matplotlib
                </div>
              </div>
              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                {/* Seaborn */}
                <div className="mx-auto">
                <Image alt=" " src={"/seaborn.png"} width={40} height={40} className="mx-auto"/>
                </div>
                <div>
                  Seaborn
                </div>
              </div>
              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                {/* Matplotlib */}
                <div className="mx-auto">
                <Image alt=" " src={"/tableau.png"} width={40} height={40} className="mx-auto"/>
                </div>
                <div>
                  Tableau
                </div>
              </div>
              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                {/* Matplotlib */}
                <div className="mx-auto">
                <Image alt=" " src={"/powerbi.png"} width={40} height={40} className="mx-auto rounded-md"/>
                </div>
                <div>
                  PowerBI
                </div>
              </div>
              </div>
              
            </div>
            <div className="col-span-2 flex  flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                alt=" "
                className="rounded-md"
                src={MachineLearning}
                width={80}
                height={80}
              />
              <h3 className=" text-gray-800 text-lg font-medium pt-2">
                Machine Learning & Deep Learning
              </h3>
              <h5 className=" text-gray-700 text-sm font-normal pb-2">
                Using
              </h5>
                <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                  <div className="mx-auto">
                  <Image alt=" "
                    src={"/scikit_learn.png"}
                    width={80}
                    height={80} className="mx-auto rounded-md"/>
                  </div>
                  <div>
                  Scikit Learn
                  </div>
                </div>
                <div className="items-left">
                <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                  Regression
                </button>
                <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                  Classification
                </button>
                <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                  Clustering
                </button>
                <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                  Regularization
                </button>
                <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                  Evaluation metrics
                </button>
                </div>

                <div className="grid grid-cols-2 gap-2" >
              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                <div className="mx-auto">
                <Image alt=" " src={"/pytorch.png"} width={30} height={30} className="mx-auto rounded-md"/>
                </div>
                <div>
                  PyTorch
                </div>
              </div>
              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                <div className="mx-auto">
                <Image alt=" " src={"/tensorflow.png"} width={30} height={30} className="mx-auto rounded-md"/>
                </div>
                <div>
                  TensorFlow
                </div>
              </div>
              </div>
              <div className="items-left">
                <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                  RNN
                </button>
                <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                  LSTM
                </button>
                <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                  Transformers
                </button>
                <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                  Generative Adversarial Networks
                </button>
                <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                  Graph Neural Network
                </button>
                <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                  Natural Language Processing (NLP)
                </button>
                <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                  Word embeddings
                </button>
                <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                  Image Feature Extraction
                </button>
                </div>
            </div>

            <div className=" flex  flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image alt=" " src={code} width={80} height={80} className="rounded-md"/>
              <h3 className="text-gray-800 text-lg font-medium pt-2">
                Coding & Databases
              </h3>
              <h5 className=" text-gray-700 text-sm font-normal pb-2">
                Using
              </h5>
              <div className="grid grid-cols-2 gap-2" >
              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                <div className="mx-auto">
                <Image alt=" "
                  src={"/Python-logo-notext.svg.png"}
                  width={40}
                  height={40} className="mx-auto rounded-md"/>
                </div>
                <div>
                  Python
                </div>
              </div>

              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                <div className="mx-auto">
                <Image alt=" "
                  src={"/java.png"}
                  width={30}
                  height={30} className="mx-auto rounded-md"/>
                </div>
                <div>
                  Java
                </div>
              </div>

              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                <div className="mx-auto">
                <Image alt=" "
                  src={"/C++-Logo.wine.png"}
                  width={70}
                  height={70} className="mx-auto rounded-md"/>
                </div>
                <div>
                  C++
                </div>
              </div>

              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                <div className="mx-auto">
                <Image alt=" "
                  src={"/sql.jpeg"}
                  width={40}
                  height={40} className="mx-auto rounded-md"/>
                </div>
                <div>
                  SQL
                </div>
              </div>

              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                <div className="mx-auto">
                <Image alt=" "
                  src={"/mysql.png"}
                  width={40}
                  height={40} className="mx-auto rounded-md"/>
                </div>
                <div>
                  MySQL
                </div>
              </div>

              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                <div className="mx-auto">
                <Image alt=" "
                  src={"/mongodb.jpeg"}
                  width={60}
                  height={60} className="mx-auto rounded-md"/>
                </div>
                <div>
                  MongoDB
                </div>
              </div>

              </div>
            </div>
            
            <div className=" flex  flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                alt=" "
                src="/aws.png"
                width={80}
                height={80}
                className="rounded-md"
              />
              <h3 className="text-gray-800 text-lg font-medium pt-8 pb-2 ">
                AWS
              </h3>
              <div className="items-left">
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                EC2
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                S3
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Lambda
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                API Gateway
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Route53
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                CloudWatch
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                KMS
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Redshift
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                DynamoDB
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                SQS
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                SNS
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Step Functions
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Quicksight
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Lex
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Connect
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Comprehend
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Transcribe
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                SageMaker
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                CloudFormation
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Cloud Development Kit (CDK)
              </button>
              </div>

            </div>
            
            <div className=" flex  flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                alt=" "
                src="/tools.png"
                width={60}
                height={60}
                className="rounded-md"
              />
              <h3 className="text-gray-800 text-lg font-medium pt-8 pb-2 ">
                Other tools
              </h3>
              <div className="grid grid-cols-2 gap-2" >
                <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                  <div className="mx-auto">
                  <Image alt=" "
                    src={"/git.png"}
                    width={40}
                    height={40} className="mx-auto rounded-md"/>
                  </div>
                  <div>
                    Git
                  </div>
                </div>

                <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                  <div className="mx-auto">
                  <Image alt=" "
                    src={"/linux.png"}
                    width={40}
                    height={40} className="mx-auto rounded-md"/>
                  </div>
                  <div>
                    Linux
                  </div>
                </div>

                <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                  <div className="mx-auto">
                  <Image alt=" "
                    src={"/docker.png"}
                    width={60}
                    height={60} className="mx-auto rounded-md"/>
                  </div>
                  <div>
                    Docker
                  </div>
                </div>

                <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                  <div className="mx-auto">
                  <Image alt=" "
                    src={"/terraform.png"}
                    width={40}
                    height={40} className="mx-auto rounded-md"/>
                  </div>
                  <div>
                    Terraform
                  </div>
                </div>

                <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                  <div className="mx-auto">
                  <Image alt=" "
                    src={"/kafka.png"}
                    width={25}
                    height={25} className="mx-auto rounded-md"/>
                  </div>
                  <div>
                    Apache Kafka
                  </div>
                </div>

                <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                  <div className="mx-auto">
                  <Image alt=" "
                    src={"/databricks.png"}
                    width={35}
                    height={35} className="mx-auto rounded-md"/>
                  </div>
                  <div>
                    Databricks
                  </div>
                </div>

                <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                <div className="mx-auto">
                <Image alt=" "
                  src={"/html.png"}
                  width={40}
                  height={40} className="mx-auto rounded-md"/>
                </div>
                <div>
                  HTML
                </div>
              </div>

              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                <div className="mx-auto">
                <Image alt=" "
                  src={"/css.png"}
                  width={40}
                  height={40} className="mx-auto rounded-md"/>
                </div>
                <div>
                  CSS
                </div>
              </div>
              </div>

             
              <div className="grid grid-cols-1 gap-1 text-gray-800 py-1 flex items-center">
                <div className="mx-auto">
                <Image alt=" "
                  src={"/flask.png"}
                  width={40}
                  height={40} className="mx-auto rounded-md"/>
                </div>
                <div>
                  Flask
                </div>
              </div>

              </div>

            
            <div className="col-span-2 flex  flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                alt=" "
                src="/cert.jpeg"
                width={50}
                height={50}
                className="rounded-md"
              />
              <h3 className="text-gray-800 text-lg font-medium pt-7 pb-2 ">
                Certifications
              </h3>
              
              <div className="grid grid-cols-6 gap-2" >
              <div className="items-center pt-4">
              <Image
                  className="rounded-md items-center"
                  alt=" "
                  src={"/michigan.jpeg"}
                  width={40}
                  height={40}
                />
              </div>
              
              <div className="col-span-5 grid grid-cols-1 gap-1 text-gray-800 py-1 flex justify-start">
                <div className="text-lg text-left">
                Applied Machine Learning in Python
                </div>
                <div className="text-md text-left">
                University of Michigan
                </div>
                <div><a href="https://drive.google.com/file/d/1l4zYuYoN8bysKg_mAuH9wk4SLRgTL0XQ/view" target="_blank" rel="noopener noreferrer"><p className="text-sm text-left">Certificate</p></a></div>
              </div>

              <div className="items-center pt-4">
              <Image
                  className="rounded-md items-center"
                  alt=" "
                  src={"/ds_iit.jpeg"}
                  width={40}
                  height={40}
                />
              </div>
              
              <div className="col-span-5 grid grid-cols-1 gap-1 text-gray-800 py-1 flex justify-start">
                <div className="text-lg text-left">
                Data Science for Engineers
                </div>
                <div className="text-md text-left">
                Indian Institute of Technology, Madras
                </div>
                <div><a href="https://drive.google.com/file/d/1Ww5bSkJXbKNukemCjXZmShqp1WRvfWLt/view" target="_blank" rel="noopener noreferrer"><p className="text-sm text-left">Certificate</p></a></div>
              </div>
              
              <div className="items-center pt-4">
              <Image
                  className="rounded-md items-center"
                  alt=" "
                  src={"/dl_ai.jpeg"}
                  width={40}
                  height={40}
                />
              </div>
              
              <div className="col-span-5 grid grid-cols-1 gap-1 text-gray-800 py-1 flex justify-start">
                <div className="text-lg text-left">
                Artificial Intelligence
                </div>
                <div className="text-md text-left">
                DeepLearning.AI
                </div>
                <div><a href="https://drive.google.com/file/d/1y8kpEmWxdpBS5T6jLTuuTwaTaUJjS0bP/view" target="_blank" rel="noopener noreferrer"><p className="text-sm text-left">Certificate</p></a></div>
              </div>

              <div className="items-center pt-4">
              <Image
                  className="rounded-md items-center"
                  alt=" "
                  src={"/infosys.jpeg"}
                  width={40}
                  height={40}
                />
              </div>
              
              <div className="col-span-5 grid grid-cols-1 gap-1 text-gray-800 py-1 flex justify-start">
                <div className="text-lg text-left">
                Infosys Certified Software Programmer
                </div>
                <div className="text-md text-left">
                Infosys
                </div>
                <div><a href="https://drive.google.com/file/d/17vk1lwGZTHVh3fyLwLADBE0GEsstrg0-/view" target="_blank" rel="noopener noreferrer"><p className="text-sm text-left">Certificate</p></a></div>
              </div>

              </div>

            </div>
          </div>
          
        </section>

        <section className="pt-2" id="career">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">CAREER</h3>
          </div>
          <div className="flex flex-col gap-5 py-2 lg:flex-row lg:flex-wrap"></div>
          <VerticalTimeline lineColor="rgba(13,148,136, 0.7)">
            <VerticalTimelineElement
              className="vertical-timeline-element--work"
              contentStyle={{
                background: "rgba(13,148,136, 0.7)",
                color: "#fff",
              }}
              contentArrowStyle={{
                borderRight: "7px solid  rgba(13,148,136, 0.7)",
              }}
              date="2011 - present"
              iconStyle={{
                background: "#fff",
                color: "#fff",
                padding: "0.5rem",
              }}
              icon={
                <div className="rounded-full mt-1">
                  <img
                    className="rounded-full"
                    src="https://www.pngitem.com/pimgs/m/35-357633_university-of-cincinnati-logo-university-of-cincinnati-college.png"
                    alt="UC"
                  ></img>
                </div>
              }
            >
              <h3 className="vertical-timeline-element-title mb-2">
                Machine Learning Engineer
              </h3>
              <div className="mb-2">
                <Accordion defaultActiveKey="0" flush>
                  <Accordion.Item eventKey="0">
                    <Accordion.Header>Video Summarization</Accordion.Header>
                    <Accordion.Body>
                      <a href="#video_summarization">
                      Video Summarization - Project
                      </a>
                    </Accordion.Body>
                  </Accordion.Item>
                </Accordion>
              </div>
              <h3 className="vertical-timeline-element-title mb-2">
                Teaching Assistant
              </h3>
              <div>
                <Accordion defaultActiveKey="0" flush>
                  <Accordion.Item eventKey="0">
                    <Accordion.Header>Machine Learning</Accordion.Header>
                    <Accordion.Body>
                      <ul className="list-disc">
                        <li>Taught concepts of machine learning algorithms - gradient descent, regression, classification, clustering, PCA.</li>
                        <li>Graded student projects & assignments</li>
                      </ul>
                                                                         
                    </Accordion.Body>
                  </Accordion.Item>
                  <Accordion.Item eventKey="1">
                    <Accordion.Header>Cloud Computing</Accordion.Header>
                    <Accordion.Body>
                    Taught students various cloud-based tools with hands-on projects:
                      <ul className="list-disc">
                      <li><b>AWS</b> - Designed an interactive web page and configured the web server using an EC2 instance.</li>
                      <li><b>GCP</b> - Developed a college inquiry chatbot using Google Dialogflow.</li>
                      <li><b>Docker</b> -Created a docker container for a simple Python script.</li>
                      <li><b>PySpark</b> - Analyzed weather data from <a href="https://www.ncei.noaa.gov/">NCEI</a> using Jupyter notebook & PySpark.</li>
                      <li><b>Databricks</b> - Performed exploratory data analysis (EDA) to gain insights on a Crime Dataset using the Community Edition of Databricks.</li>
                      </ul>
                      </Accordion.Body>
                  </Accordion.Item>
                  <Accordion.Item eventKey="2">
                    <Accordion.Header>Data Structures</Accordion.Header>
                    <Accordion.Body>
                    <ul className="list-disc">
                      <li>Taught OOPS concepts and Data Structures - Arrays, LinkedList, Stacks, Queues, and Trees.</li>
                      <li>Hosted weekly office hours and lab sessions to solve student queries in programming concepts.</li>
                    </ul>
                    </Accordion.Body>
                  </Accordion.Item>
                </Accordion>
              </div>
              <p>University of Cincinnati</p>
            </VerticalTimelineElement>
            <VerticalTimelineElement
              className="vertical-timeline-element--work"
              contentStyle={{
                background: "rgba(13,148,136, 0.7)",
                color: "#fff",
              }}
              contentArrowStyle={{
                borderRight: "7px solid  rgba(13,148,136, 0.7)",
              }}
              date="2011 - present"
              iconStyle={{
                background: "#fff",
                color: "#fff",
                padding: "0.5rem",
              }}
              icon={
                <div className="rounded-full mt-1">
                  <img
                    className="rounded-full"
                    src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Amazon_icon.svg/2500px-Amazon_icon.svg.png"
                    alt="Amazon Inc."
                  ></img>
                </div>
              }
            >
              <h3 className="vertical-timeline-element-title mb-2">
                System Development Intern
              </h3>
              <div className="mb-2">
                <Accordion defaultActiveKey="0" flush>
                  <Accordion.Item eventKey="0">
                    <Accordion.Header>SPT Analysis Automation</Accordion.Header>
                    <Accordion.Body>
                    Developed an automation tool, using AWS services and Python, that gives insights from metrics during Service Performance Testing, which reduced the analysis time significantly from 30 mins when manually done to 1 min.                    </Accordion.Body>
                  </Accordion.Item>
                  <Accordion.Item eventKey="1">
                    <Accordion.Header>IRS Enhancement</Accordion.Header>
                    <Accordion.Body>
                    Enhanced the Incident Resolver Automation tool to solve the tickets issued from MonitorPortal using AWS and Java.
                    </Accordion.Body>
                  </Accordion.Item>
                </Accordion>
              </div>

              <p>Amazon Inc.</p>
            </VerticalTimelineElement>
            <VerticalTimelineElement
              className="vertical-timeline-element--work"
              contentStyle={{
                background: "rgba(13,148,136, 0.7)",
                color: "#fff",
              }}
              contentArrowStyle={{
                borderRight: "7px solid  rgba(13,148,136, 0.7)",
              }}
              date="2011 - present"
              iconStyle={{
                background: "#fff",
                color: "#fff",
                padding: "0.5rem",
              }}
              icon={
                <div className="rounded-full mt-1">
                  <img
                    className="rounded-full"
                    src="https://media.glassdoor.com/sqll/235160/qvantel-squarelogo-1454999377271.png"
                    alt="Qvantel"
                  ></img>
                </div>
              }
            >
              <h3 className="vertical-timeline-element-title mb-2">
                Machine Learning Engineer [Innovation Team]
              </h3>
              <div className="mb-2">
                <Accordion defaultActiveKey="0" flush>
                  <Accordion.Item eventKey="0">
                    <Accordion.Header>
                      Trending Analysis of Social Media
                    </Accordion.Header>
                    <Accordion.Body>
                      <ul className="list-disc">
                      <li>Extracted tweets related to the telecom industry and Qvantel organization using Twitter API.</li>
                      <li>Analyzed the activity on the tweets, performed sentiment analysis, and derived insights.</li>
                      </ul>
                    
                    <Image
                      className="w-full mb-2 rounded-xl border border-gray-200 shadow-sm shadow-gray-50"
                      src="/tasm.jpg"
                      alt="Project photo"
                      width={800}
                      height={240}
                    />
                    </Accordion.Body>
                  </Accordion.Item>
                  <Accordion.Item eventKey="1">
                    <Accordion.Header>
                      AI Chatbot
                    </Accordion.Header>
                    <Accordion.Body>
                    Built a Chatbot and integrated analytics tools to get deep insights into the customer experience.
                    <Image
                      className="w-full mb-2 rounded-xl border border-gray-200 shadow-sm shadow-gray-50"
                      src="/chatbot.png"
                      alt="Project photo"
                      width={800}
                      height={240}
                    />
                    </Accordion.Body>
                  </Accordion.Item>
                  <Accordion.Item eventKey="2">
                    <Accordion.Header>
                      Facebook Messenger Chatbot
                    </Accordion.Header>
                    <Accordion.Body>
                    Integrated the AI Chatbot with Facebook Messenger.
                    </Accordion.Body>
                  </Accordion.Item>
                  <Accordion.Item eventKey="3">
                    <Accordion.Header>AI powered Call Center</Accordion.Header>
                    <Accordion.Body>
                    Established a virtual call center using AWS Connect and performed sentiment analysis on caller interaction.
                    <Image
                      className="w-full mb-2 rounded-xl border border-gray-200 shadow-sm shadow-gray-50"
                      src="/contact_center.png"
                      alt="Project photo"
                      width={800}
                      height={240}
                    />
                    </Accordion.Body>
                  </Accordion.Item>
                </Accordion>
              </div>

              <p>Qvantel Software Solutions</p>
            </VerticalTimelineElement>
            <VerticalTimelineElement
              className="vertical-timeline-element--work"
              contentStyle={{
                background: "rgba(13,148,136, 0.7)",
                color: "#fff",
              }}
              contentArrowStyle={{
                borderRight: "7px solid  rgba(13,148,136, 0.7)",
              }}
              date="2011 - present"
              iconStyle={{
                background: "#fff",
                color: "#fff",
                padding: "0.5rem",
              }}
              icon={
                <div className="rounded-full mt-1">
                  <img
                    className="rounded-full"
                    src="http://www.iiitnr.ac.in/sites/all/themes/iiit/G_300res.png"
                    alt="IIIT"
                  ></img>
                </div>
              }
            >
              <h3 className="vertical-timeline-element-title mb-2">
                Machine Learning Intern
              </h3>
              <div className="mb-2">
                <Accordion defaultActiveKey="0" flush>
                  <Accordion.Item eventKey="0">
                    <Accordion.Header>
                      Machine Health Prediction
                    </Accordion.Header>
                    <Accordion.Body>
                      <a href="#mhp">
                      Machine Health Prediction - Project
                      </a>
                    </Accordion.Body>
                  </Accordion.Item>
                </Accordion>
              </div>

              <p>International Institute of Information Technology (IIIT)</p>
            </VerticalTimelineElement>
            <VerticalTimelineElement
              className="vertical-timeline-element--work"
              contentStyle={{
                background: "rgba(13,148,136, 0.7)",
                color: "#fff",
              }}
              contentArrowStyle={{
                borderRight: "7px solid  rgba(13,148,136, 0.7)",
              }}
              date="2011 - present"
              iconStyle={{
                background: "#fff",
                color: "#fff",
                padding: "0.5rem",
              }}
              icon={
                <div className="rounded-full mt-2">
                  <img
                    src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Tech_Mahindra_New_Logo.svg/1200px-Tech_Mahindra_New_Logo.svg.png"
                    alt="Tech Mahindra"
                  ></img>
                </div>
              }
            >
              <h3 className="vertical-timeline-element-title mb-2">
                Data Science Intern
              </h3>
              <div className="mb-2">
                <Accordion defaultActiveKey="0" flush>
                  <Accordion.Item eventKey="0">
                    <Accordion.Header>
                      Restaurant Recommendation System
                    </Accordion.Header>
                    <Accordion.Body>
                      <ul className="list-disc">
                      <li>Developed an end-to-end data-driven workflow architecture for the Restaurant Recommender system on Azure AutoML.</li>
                      <li>Performed Data Visualization of the SQL database using PowerBI.</li>
                      </ul>
                    </Accordion.Body>
                  </Accordion.Item>
                </Accordion>
              </div>

              <p>Tech Mahindra Inc.</p>
            </VerticalTimelineElement>
          </VerticalTimeline>
        </section>
        
        <section className="pt-10" id="portfolio">
        <div className="mb-10">
            <h3 className="text-3xl py-1 dark:text-white">PORTFOLIO</h3>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 mt-2 lg:grid-cols-2 gap-6 dark:text-white">

        <div className="flex flex-col rounded-xl dark:bg-white" id="video_summarization">
            <Image
              className="w-full mb-2 rounded-xl border border-gray-200 shadow-sm shadow-gray-50"
              src="/vs_crop.png"
              alt="Project photo"
              width={800}
              height={240}
            />
            <p className="text-md text-gray-900 mb-1 mt-2 font-semibold group-hover:underline group-hover:underline-offset-4">
              Video Summarization
            </p>

            <div className="items-left">
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Video Processing
            </button>
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Deep Learning
            </button>
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                  Image Pre-processing
            </button>
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Image feature extraction
            </button>
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                GoogleNet
            </button>
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                ResNet
            </button>
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Generative Adversarial Networks
            </button>
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Graph modelling
            </button>
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Graph Neural Networks
            </button>
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
              Transformer
            </button>
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
              Self-Attention
            </button>
            </div>

            <div className="flex items-center">
              <a href="https://github.com/jeshmitha/Video_Summarization" className="items-center">
                <button className="mr-2 items-center mt-0 rounded-full text-sm  border-0 text-gray-900 ml-0 py-0.5 flex px-1 hover:underline-offset-2 hover:underline hover:text-ds_blue">
              
              <svg width="1024" height="1024" viewBox="0 0 1024 1024" className="h-5 w-5 mr-1" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8C0 11.54 2.29 14.53 5.47 15.59C5.87 15.66 6.02 15.42 6.02 15.21C6.02 15.02 6.01 14.39 6.01 13.72C4 14.09 3.48 13.23 3.32 12.78C3.23 12.55 2.84 11.84 2.5 11.65C2.22 11.5 1.82 11.13 2.49 11.12C3.12 11.11 3.57 11.7 3.72 11.94C4.44 13.15 5.59 12.81 6.05 12.6C6.12 12.08 6.33 11.73 6.56 11.53C4.78 11.33 2.92 10.64 2.92 7.58C2.92 6.71 3.23 5.99 3.74 5.43C3.66 5.23 3.38 4.41 3.82 3.31C3.82 3.31 4.49 3.1 6.02 4.13C6.66 3.95 7.34 3.86 8.02 3.86C8.7 3.86 9.38 3.95 10.02 4.13C11.55 3.09 12.22 3.31 12.22 3.31C12.66 4.41 12.38 5.23 12.3 5.43C12.81 5.99 13.12 6.7 13.12 7.58C13.12 10.65 11.25 11.33 9.47 11.53C9.76 11.78 10.01 12.26 10.01 13.01C10.01 14.08 10 14.94 10 15.21C10 15.42 10.15 15.67 10.55 15.59C13.71 14.53 16 11.53 16 8C16 3.58 12.42 0 8 0Z" transform="scale(64)" fill="currentColor"></path></svg>
                  GitHub
                </button>
              </a>  
            </div>
          
            <p className="text-sm text-gray-600 mb-1 mt-2 dark:text-white">
            Developed an automatic video summarization model by combining attention mechanism with graph modeling techniques and using VAE-GAN(Variational Autoencoder - Generative Adversarial Network) architecture with transformer encoder.
            </p>
          </div>

          <div className="flex flex-col rounded-xl dark:bg-white">
            <Image
              className="w-full mb-2 rounded-xl border border-gray-200 shadow-sm shadow-gray-50"
              src="/efp_crop.png"
              alt="Project photo"
              width={800}
              height={240}
            />
            <p className="text-md text-gray-900 mb-1 mt-2 font-semibold group-hover:underline group-hover:underline-offset-4">
              Engine Failure Prediction
            </p>
            <p className="text-sm mb-0 font-semibold text-gray-900 flex items-center">
            <Image
              alt=" "
              src="/cert.jpeg"
              width={25}
              height={25}
              className="rounded-md pr-1"
            />
            Won 2<sup>nd</sup> prize in VIGNITE National Hackathon
            </p>

            <div className="items-left">
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Predictive Maintenance
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                IoT
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                MQTT
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Firebase
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Machine Learning
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Classification
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Support Vector Machine(SVM)
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Android App
              </button>
            </div>

            <div className="flex items-center">
              <a href="https://github.com/jeshmitha/Engine_Failure_Prediction" className="items-center">
                <button className="mr-2 items-center mt-0 rounded-full text-sm  border-0 text-gray-900 ml-0 py-0.5 flex px-1 hover:underline-offset-2 hover:underline hover:text-ds_blue">
              
              <svg width="1024" height="1024" viewBox="0 0 1024 1024" className="h-5 w-5 mr-1" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8C0 11.54 2.29 14.53 5.47 15.59C5.87 15.66 6.02 15.42 6.02 15.21C6.02 15.02 6.01 14.39 6.01 13.72C4 14.09 3.48 13.23 3.32 12.78C3.23 12.55 2.84 11.84 2.5 11.65C2.22 11.5 1.82 11.13 2.49 11.12C3.12 11.11 3.57 11.7 3.72 11.94C4.44 13.15 5.59 12.81 6.05 12.6C6.12 12.08 6.33 11.73 6.56 11.53C4.78 11.33 2.92 10.64 2.92 7.58C2.92 6.71 3.23 5.99 3.74 5.43C3.66 5.23 3.38 4.41 3.82 3.31C3.82 3.31 4.49 3.1 6.02 4.13C6.66 3.95 7.34 3.86 8.02 3.86C8.7 3.86 9.38 3.95 10.02 4.13C11.55 3.09 12.22 3.31 12.22 3.31C12.66 4.41 12.38 5.23 12.3 5.43C12.81 5.99 13.12 6.7 13.12 7.58C13.12 10.65 11.25 11.33 9.47 11.53C9.76 11.78 10.01 12.26 10.01 13.01C10.01 14.08 10 14.94 10 15.21C10 15.42 10.15 15.67 10.55 15.59C13.71 14.53 16 11.53 16 8C16 3.58 12.42 0 8 0Z" transform="scale(64)" fill="currentColor"></path></svg>
                  GitHub
                </button>
              </a>  
            </div>
          
            <p className="text-sm text-gray-600 mb-1 mt-2 dark:text-white">
            An end-to-end system that predicts any machine malfunction weeks by tracking live data from sensors and automatically turns off the machine without any human intervention while sending notifications to the owner.
            </p>
          </div>


          <div className="flex flex-col rounded-xl dark:bg-white">
            <Image
              className="w-full mb-2 rounded-xl border border-gray-200 shadow-sm shadow-gray-50"
              src="/ser_crop_1.png"
              alt="Project photo"
              width={800}
              height={240}
            />
            <p className="text-md text-gray-900 mb-1 mt-2 font-semibold group-hover:underline group-hover:underline-offset-4">
              Speech Emotion Recognition
            </p>

            <div className="items-left">
            
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Audio Feature Extraction
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Audio Pre-processing
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Deep Learning
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                PyTorch
              </button>
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                CNN
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                LSTM
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                CapsuleNet
              </button>
              
              
            </div>

            <div className="flex items-center">
              <a href="https://github.com/jeshmitha/Speech-Emotion-Recognition" className="items-center">
                <button className="mr-2 items-center mt-0 rounded-full text-sm  border-0 text-gray-900 ml-0 py-0.5 flex px-1 hover:underline-offset-2 hover:underline hover:text-ds_blue">
              
              <svg width="1024" height="1024" viewBox="0 0 1024 1024" className="h-5 w-5 mr-1" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8C0 11.54 2.29 14.53 5.47 15.59C5.87 15.66 6.02 15.42 6.02 15.21C6.02 15.02 6.01 14.39 6.01 13.72C4 14.09 3.48 13.23 3.32 12.78C3.23 12.55 2.84 11.84 2.5 11.65C2.22 11.5 1.82 11.13 2.49 11.12C3.12 11.11 3.57 11.7 3.72 11.94C4.44 13.15 5.59 12.81 6.05 12.6C6.12 12.08 6.33 11.73 6.56 11.53C4.78 11.33 2.92 10.64 2.92 7.58C2.92 6.71 3.23 5.99 3.74 5.43C3.66 5.23 3.38 4.41 3.82 3.31C3.82 3.31 4.49 3.1 6.02 4.13C6.66 3.95 7.34 3.86 8.02 3.86C8.7 3.86 9.38 3.95 10.02 4.13C11.55 3.09 12.22 3.31 12.22 3.31C12.66 4.41 12.38 5.23 12.3 5.43C12.81 5.99 13.12 6.7 13.12 7.58C13.12 10.65 11.25 11.33 9.47 11.53C9.76 11.78 10.01 12.26 10.01 13.01C10.01 14.08 10 14.94 10 15.21C10 15.42 10.15 15.67 10.55 15.59C13.71 14.53 16 11.53 16 8C16 3.58 12.42 0 8 0Z" transform="scale(64)" fill="currentColor"></path></svg>
                  GitHub
                </button>
              </a>  
              <a href="https://link.springer.com/chapter/10.1007/978-3-031-09469-9_22" target="_blank" className="items-center">
                <button className="mr-2 items-center mt-0 rounded-full text-sm  border-0 text-gray-900 ml-0 py-0.5 flex px-1 hover:underline-offset-2 hover:underline hover:text-ds_blue">

                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-1" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M12.586 4.586a2 2 0 112.828 2.828l-3 3a2 2 0 01-2.828 0 1 1 0 00-1.414 1.414 4 4 0 005.656 0l3-3a4 4 0 00-5.656-5.656l-1.5 1.5a1 1 0 101.414 1.414l1.5-1.5zm-5 5a2 2 0 012.828 0 1 1 0 101.414-1.414 4 4 0 00-5.656 0l-3 3a4 4 0 105.656 5.656l1.5-1.5a1 1 0 10-1.414-1.414l-1.5 1.5a2 2 0 11-2.828-2.828l3-3z" clip-rule="evenodd"></path>
                  </svg> Paper
                </button>
              </a>
            </div>
          
            <p className="text-sm text-gray-600 mb-1 mt-2 dark:text-white">
            Extracted MFCC features from audio recordings and trained the CapsuleNet & CNN-LSTM deep learning models. Achieved state-of-the-art 94.01% performance accuracy with the CapsuleNet model, which outperformed traditional models.
            </p>
          </div>

          <div className="flex flex-col rounded-xl dark:bg-white" id="mhp">
            <Image
              className="w-full mb-2 rounded-xl border border-gray-200 shadow-sm shadow-gray-50"
              src="/mhp_crop.png"
              alt="Project photo"
              width={800}
              height={240}
            />
            <p className="text-md text-gray-900 mb-1 mt-2 font-semibold group-hover:underline group-hover:underline-offset-4">
              Machine Health Prediction
            </p>

            <div className="items-left">
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Predictive Maintenance
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Decision Tree
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                XGBoost
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                KNN
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                SVM
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Flask
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Android App
              </button>
            </div>

            <div className="flex items-center">
              <a href="https://github.com/jeshmitha/machine-health-prediction" className="items-center">
                <button className="mr-2 items-center mt-0 rounded-full text-sm  border-0 text-gray-900 ml-0 py-0.5 flex px-1 hover:underline-offset-2 hover:underline hover:text-ds_blue">
              
              <svg width="1024" height="1024" viewBox="0 0 1024 1024" className="h-5 w-5 mr-1" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8C0 11.54 2.29 14.53 5.47 15.59C5.87 15.66 6.02 15.42 6.02 15.21C6.02 15.02 6.01 14.39 6.01 13.72C4 14.09 3.48 13.23 3.32 12.78C3.23 12.55 2.84 11.84 2.5 11.65C2.22 11.5 1.82 11.13 2.49 11.12C3.12 11.11 3.57 11.7 3.72 11.94C4.44 13.15 5.59 12.81 6.05 12.6C6.12 12.08 6.33 11.73 6.56 11.53C4.78 11.33 2.92 10.64 2.92 7.58C2.92 6.71 3.23 5.99 3.74 5.43C3.66 5.23 3.38 4.41 3.82 3.31C3.82 3.31 4.49 3.1 6.02 4.13C6.66 3.95 7.34 3.86 8.02 3.86C8.7 3.86 9.38 3.95 10.02 4.13C11.55 3.09 12.22 3.31 12.22 3.31C12.66 4.41 12.38 5.23 12.3 5.43C12.81 5.99 13.12 6.7 13.12 7.58C13.12 10.65 11.25 11.33 9.47 11.53C9.76 11.78 10.01 12.26 10.01 13.01C10.01 14.08 10 14.94 10 15.21C10 15.42 10.15 15.67 10.55 15.59C13.71 14.53 16 11.53 16 8C16 3.58 12.42 0 8 0Z" transform="scale(64)" fill="currentColor"></path></svg>
                  GitHub
                </button>
              </a>  
            </div>
          
            <p className="text-sm text-gray-600 mb-1 mt-2 dark:text-white">
            Developed an end-to-end system for “Prognostic System Health Management” by building an android application to monitor and predict the machine’s health condition that could help the industry environment by providing advanced alerts.
            </p>
          </div>

          <div className="flex flex-col rounded-xl dark:bg-white">
            <Image
              className="w-full mb-2 rounded-xl border border-gray-200 shadow-sm shadow-gray-50"
              src="/yelp_crop.png"
              alt="Project photo"
              width={800}
              height={240}
            />
            <p className="text-md text-gray-900 mb-1 mt-2 font-semibold group-hover:underline group-hover:underline-offset-4">
              Yelp Restaurant Data Scraping
            </p>

            <div className="items-left">
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Web Scraping
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Beautiful Soup
              </button>
            </div>

            <div className="flex items-center">
              <a href="https://github.com/jeshmitha/Web_Scraping-Yelp_Restaurant_Data" className="items-center">
                <button className="mr-2 items-center mt-0 rounded-full text-sm  border-0 text-gray-900 ml-0 py-0.5 flex px-1 hover:underline-offset-2 hover:underline hover:text-ds_blue">
              
              <svg width="1024" height="1024" viewBox="0 0 1024 1024" className="h-5 w-5 mr-1" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8C0 11.54 2.29 14.53 5.47 15.59C5.87 15.66 6.02 15.42 6.02 15.21C6.02 15.02 6.01 14.39 6.01 13.72C4 14.09 3.48 13.23 3.32 12.78C3.23 12.55 2.84 11.84 2.5 11.65C2.22 11.5 1.82 11.13 2.49 11.12C3.12 11.11 3.57 11.7 3.72 11.94C4.44 13.15 5.59 12.81 6.05 12.6C6.12 12.08 6.33 11.73 6.56 11.53C4.78 11.33 2.92 10.64 2.92 7.58C2.92 6.71 3.23 5.99 3.74 5.43C3.66 5.23 3.38 4.41 3.82 3.31C3.82 3.31 4.49 3.1 6.02 4.13C6.66 3.95 7.34 3.86 8.02 3.86C8.7 3.86 9.38 3.95 10.02 4.13C11.55 3.09 12.22 3.31 12.22 3.31C12.66 4.41 12.38 5.23 12.3 5.43C12.81 5.99 13.12 6.7 13.12 7.58C13.12 10.65 11.25 11.33 9.47 11.53C9.76 11.78 10.01 12.26 10.01 13.01C10.01 14.08 10 14.94 10 15.21C10 15.42 10.15 15.67 10.55 15.59C13.71 14.53 16 11.53 16 8C16 3.58 12.42 0 8 0Z" transform="scale(64)" fill="currentColor"></path></svg>
                  GitHub
                </button>
              </a>  
            </div>
          
            <p className="text-sm text-gray-600 mb-1 mt-2 dark:text-white">
            Scrape information about restaurants in major cities of the US from Yelp using Python and BeautifulSoup.
            </p>
          </div>

          <div className="flex flex-col rounded-xl dark:bg-white">
            <Image
              className="w-full mb-2 rounded-xl border border-gray-200 shadow-sm shadow-gray-50"
              src="/flight_delay_crop.jpeg"
              alt="Project photo"
              width={800}
              height={240}
            />
            <p className="text-md text-gray-900 mb-1 mt-2 font-semibold group-hover:underline group-hover:underline-offset-4">
              Flight Delay Prediction
            </p>

            <div className="items-left">
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Machine Learning
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Regression
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Classification
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                XGBoost
            </button>
            </div>

            <div className="flex items-center">
              <a href="https://github.com/jeshmitha/Flight_Delay_Prediction" className="items-center">
                <button className="mr-2 items-center mt-0 rounded-full text-sm  border-0 text-gray-900 ml-0 py-0.5 flex px-1 hover:underline-offset-2 hover:underline hover:text-ds_blue">
              
              <svg width="1024" height="1024" viewBox="0 0 1024 1024" className="h-5 w-5 mr-1" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8C0 11.54 2.29 14.53 5.47 15.59C5.87 15.66 6.02 15.42 6.02 15.21C6.02 15.02 6.01 14.39 6.01 13.72C4 14.09 3.48 13.23 3.32 12.78C3.23 12.55 2.84 11.84 2.5 11.65C2.22 11.5 1.82 11.13 2.49 11.12C3.12 11.11 3.57 11.7 3.72 11.94C4.44 13.15 5.59 12.81 6.05 12.6C6.12 12.08 6.33 11.73 6.56 11.53C4.78 11.33 2.92 10.64 2.92 7.58C2.92 6.71 3.23 5.99 3.74 5.43C3.66 5.23 3.38 4.41 3.82 3.31C3.82 3.31 4.49 3.1 6.02 4.13C6.66 3.95 7.34 3.86 8.02 3.86C8.7 3.86 9.38 3.95 10.02 4.13C11.55 3.09 12.22 3.31 12.22 3.31C12.66 4.41 12.38 5.23 12.3 5.43C12.81 5.99 13.12 6.7 13.12 7.58C13.12 10.65 11.25 11.33 9.47 11.53C9.76 11.78 10.01 12.26 10.01 13.01C10.01 14.08 10 14.94 10 15.21C10 15.42 10.15 15.67 10.55 15.59C13.71 14.53 16 11.53 16 8C16 3.58 12.42 0 8 0Z" transform="scale(64)" fill="currentColor"></path></svg>
                  GitHub
                </button>
              </a>  
              <a href="https://ieeexplore.ieee.org/document/9243339" target="_blank" className="items-center">
                <button className="mr-2 items-center mt-0 rounded-full text-sm  border-0 text-gray-900 ml-0 py-0.5 flex px-1 hover:underline-offset-2 hover:underline hover:text-ds_blue">
                  
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-1" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M12.586 4.586a2 2 0 112.828 2.828l-3 3a2 2 0 01-2.828 0 1 1 0 00-1.414 1.414 4 4 0 005.656 0l3-3a4 4 0 00-5.656-5.656l-1.5 1.5a1 1 0 101.414 1.414l1.5-1.5zm-5 5a2 2 0 012.828 0 1 1 0 101.414-1.414 4 4 0 00-5.656 0l-3 3a4 4 0 105.656 5.656l1.5-1.5a1 1 0 10-1.414-1.414l-1.5 1.5a2 2 0 11-2.828-2.828l3-3z" clip-rule="evenodd"></path>
                  </svg> Paper
                </button>
              </a>
            </div>
          
            <p className="text-sm text-gray-600 mb-1 mt-2 dark:text-white">
            Developed a model to predict the arrival delay of flights at the destination airport using supervised ML algorithms - XGBoost and Regression models.
            </p>
          </div>

          <div className="flex flex-col rounded-xl dark:bg-white">
            <Image
              className="w-full mb-2 rounded-xl border border-gray-200 shadow-sm shadow-gray-50"
              src="/airbnb_crop.png"
              alt="Project photo"
              width={800}
              height={240}
            />
            <p className="text-md text-gray-900 mb-1 mt-2 font-semibold group-hover:underline group-hover:underline-offset-4">
              Airbnb Data Analysis
            </p>

            <div className="items-left">
            <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Exploratory Data Analysis
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Univariate Analysis
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Multivariate Analysis
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Data Pre-processing
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Hypothesis Testing
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Data Visualisation
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Matplotlib
              </button>
              <button className="px-2 py-0.5 rounded-full text-xs font-sm bg-sky-100 text-blue-600 mr-1 mb-1">
                Seaborn
              </button>
            </div>

            <div className="flex items-center">
              <a href="https://github.com/jeshmitha/Airbnb_Data_Analysis" className="items-center">
                <button className="mr-2 items-center mt-0 rounded-full text-sm  border-0 text-gray-900 ml-0 py-0.5 flex px-1 hover:underline-offset-2 hover:underline hover:text-ds_blue">
              
              <svg width="1024" height="1024" viewBox="0 0 1024 1024" className="h-5 w-5 mr-1" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8C0 11.54 2.29 14.53 5.47 15.59C5.87 15.66 6.02 15.42 6.02 15.21C6.02 15.02 6.01 14.39 6.01 13.72C4 14.09 3.48 13.23 3.32 12.78C3.23 12.55 2.84 11.84 2.5 11.65C2.22 11.5 1.82 11.13 2.49 11.12C3.12 11.11 3.57 11.7 3.72 11.94C4.44 13.15 5.59 12.81 6.05 12.6C6.12 12.08 6.33 11.73 6.56 11.53C4.78 11.33 2.92 10.64 2.92 7.58C2.92 6.71 3.23 5.99 3.74 5.43C3.66 5.23 3.38 4.41 3.82 3.31C3.82 3.31 4.49 3.1 6.02 4.13C6.66 3.95 7.34 3.86 8.02 3.86C8.7 3.86 9.38 3.95 10.02 4.13C11.55 3.09 12.22 3.31 12.22 3.31C12.66 4.41 12.38 5.23 12.3 5.43C12.81 5.99 13.12 6.7 13.12 7.58C13.12 10.65 11.25 11.33 9.47 11.53C9.76 11.78 10.01 12.26 10.01 13.01C10.01 14.08 10 14.94 10 15.21C10 15.42 10.15 15.67 10.55 15.59C13.71 14.53 16 11.53 16 8C16 3.58 12.42 0 8 0Z" transform="scale(64)" fill="currentColor"></path></svg>
                  GitHub
                </button>
              </a>  
            </div>
          
            <p className="text-sm text-gray-600 mb-1 mt-2 dark:text-white">
            Performed exploratory data analysis on Airbnb Data in the US (New York) using python data visualization libraries. Visualized insights on customer behavior, market demand, and location impact.
            </p>
          </div>
        </div>

        </section>

        <section className="pt-10" id="getintouch">
        <div>
          <h3 className="text-3xl py-1 dark:text-white">GET IN TOUCH</h3>
        </div>
        <div className="  text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
          <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white" href="https://www.linkedin.com/in/jeshmitha/"> <AiFillLinkedin  /></a>
          <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white" href="https://github.com/jeshmitha"> <AiFillGithub /></a>
          <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white" href="mailto: jeshmitha.gunuganti@gmail.com"> <AiFillMail /> </a>
        </div>
        </section>

      </main>
    </div>
  );
}
